name: game_plus
description: "A cute casual game hub built with Flutter ğŸ®"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
    

  # Icon iOS style
  cupertino_icons: ^1.0.8

  # Ã‚m thanh / nháº¡c ná»n / click
  audioplayers: ^5.2.1

  # LÆ°u cÃ i Ä‘áº·t local (volume, theme, language, ...)
  shared_preferences: ^2.3.2

  # Animation mÆ°á»£t + hero transition nÃ¢ng cao
  flutter_animate: ^4.5.0

  # Hiá»‡u á»©ng chuyá»ƒn trang Ä‘áº¹p (fade, slide, scale,â€¦)
  page_transition: ^2.1.0

  # Äiá»u khiá»ƒn Ä‘á»™ sÃ¡ng / dark mode (náº¿u muá»‘n thÃªm)
  dynamic_color: ^1.7.0

  # Hiá»ƒn thá»‹ icon vector (SVG)
  flutter_svg: ^2.0.10+1

  # ThÆ° viá»‡n há»— trá»£ UI bo trÃ²n, bÃ³ng Ä‘áº¹p, responsive
  flutter_screenutil: ^5.9.0

  # Hiá»‡u á»©ng rung thiáº¿t bá»‹
  vibration: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sfx/
    - assets/fonts/
    - assets/sounds/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
